export const SVC_BUSINESS_PROCESS_LIST = ():string => '/svc/business-process/';
export const SVC_BUSINESS_PROCESS_GET = (code: string): string => `/svc/business-process/${code}`;
export const SVC_BUSINESS_PROCESS_GET_ASSIGNED_ROLES = (code: string): string => `/svc/business-process/${code}/assigned-roles/`;
export const SVC_ROLE_LIST = (): string => `/svc/role/`;
export const SVC_ROLE_GET = (code: string): string => `/svc/role/${code}`;
export const SVC_APPLICATION_LIST = (): string => `/svc/application/`;
export const SVC_APPLICATION_GET = (code: string): string => `/svc/application/${code}`;
export const SVC_IT_SYSTEM_LIST = (): string => `/svc/it-system/`;
export const SVC_IT_SYSTEM_GET = (code: string): string => `/svc/it-system/${code}`;
export const SVC_ENUM_MODULE_LIST = (): string => `/svc/enum/module-type/`;

export const UI_BSI_MODULE_LIST = (): string => `/bsi-module`;
export const UI_BSI_MODULE_GET = (entity: any): string => `/bsi-module/${entity.code}`;
export const UI_BUSINESS_PROCESS_LIST = (): string => `/organization-info/business-process`;
export const UI_BUSINESS_PROCESS_GET = (entity: any): string => `/organization-info/business-process/${entity.code}`;
export const UI_ROLE_LIST = (): string => `/organization-info/role`;
export const UI_ROLE_GET = (entity: any): string => `/organization-info/role/${entity.code}`;
export const UI_APPLICATION_LIST = (): string => `/organization-info/application`;
export const UI_APPLICATION_GET = (entity: any): string => `/organization-info/application/${entity.code}`;
export const UI_IT_SYSTEM_LIST = (): string => `/organization-info/it-system`;
export const UI_IT_SYSTEM_GET = (entity: any): string => `/organization-info/it-system/${entity.code}`;